"""create table meta_tags

Revision ID: ac819c565749
Revises: 
Create Date: 2021-07-21 19:13:37.342291

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ac819c565749'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meta_tags',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.TEXT(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', 'slug'),
    schema='public'
    )
    op.create_index(op.f('ix_public_meta_tags_slug'), 'meta_tags', ['slug'], unique=True, schema='public')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_meta_tags_slug'), table_name='meta_tags', schema='public')
    op.drop_table('meta_tags', schema='public')
    # ### end Alembic commands ###
